version: '2'
services:
    vas:
        image: vas:latest
        build: .
        container_name: vas_dc
        restart: always
        ports:
            - 127.0.0.1:8012:8000
#            - 127.0.0.1:8080:8080
#        command: [sh, -c, "install -m 0755 -o www-data -g www-data -d /var/log/uwsgi && uwsgi --yaml /etc/uwsgi.yaml"]
#        env_file:
#          - .env
        environment:
#            - MAIL_SERVER=smtp.yandex.ru
#            - MAIL_PORT=465
#            - MAIL_USE_SSL=1
#            - MAIL_USERNAME=mail@it-depart.ru
#            - MAIL_PASSWORD=081216Itdepart
#            - YA_TRANSLATOR_KEY=trnsl.1.1.20180602T134147Z.296ec2219a057a0d.cd86167a0c61236c7723c1373e145ddc18028143
#            - DATABASE_URL=mysql+pymysql://otsmgps:121asdfFFFfff3dsfh23@dbserver/otsmgps
#            - SERVER_NAME=otsmgps.it-depart.ru
#            - DATABASE_URL=mysql+pymysql://root:5yjej367@dbserver/portal
            - DEBUG_VALUE=FALSE
#            - CELERY_BROKER_URL=redis://redis/0
            - CELERY_BROKER_URL=amqp://vas_u:asd24sdg125@rabbit/
            - DATABASE_BACKENDS_MYSQL=TRUE
            - DB_USER=vas
            - DB_PASSWORD=dsf2346dfhyjq2236789
            - DB_HOST=mysql
#            - DB_PORT=3307
            - DB_NAME=vas
#            - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
        links:
            - mysql:dbserver
#            - redis:redis
#            - elasticsearch:elasticsearch
        depends_on:
            - mysql
#            - redis
        volumes:
            - ./www:/home/vas/vas:rw

    mysql:
        image: mysql/mysql-server:5.7
        container_name: vas_dc_mysql
        restart: always
        ports:
            - 127.0.0.1:3315:3306
        environment:
            - MYSQL_ROOT_PASSWORD=3tgew24523
            - MYSQL_DATABASE=vas
            - MYSQL_USER=vas
            - MYSQL_PASSWORD=dsf2346dfhyjq2236789
        volumes:
             - ./my.cnf:/etc/my.cnf:ro

#    redis:
#        image: redis:latest
#        container_name: vkbot_dc_redis
#        restart: always
        #sysctls:
        #    - vm.overcommit_memory=1
        #    - net.core.somaxconn=511


    # RabbitMQ - queue
#    rabbit:
#        hostname: rabbit
#        image: rabbitmq:3-management
#        build:
#            context: .
#            dockerfile: Dockerfile_rabbitmq
#        command: sh ./run_rabbit.sh
#        restart: always
#        environment:
#            - RABBITMQ_USER=vkbot_u
#            - RABBITMQ_PASSWORD=asd24sdg125
##            - RABBITMQ_DEFAULT_USER=vkbot_admin
##            - RABBITMQ_DEFAULT_PASS=asd24sdg125
#        ports:
#            - "5672:5672"
#            - "15672:15672"  # here, we can access rabbitmq management plugin

    # Celery worker
#    worker:
#        build:
#            context: .
#            dockerfile: Dockerfile_celery
#        command: sh ./run_celery.sh
#        restart: always
#        volumes:
#            - .:/app
#        environment:
#            - DEBUG_VALUE=FALSE
#            - CELERY_BROKER_URL=amqp://vkbot_u:asd24sdg125@rabbit/
##            - CELERY_BROKER_URL=redis://redis/0
#            - DATABASE_BACKENDS_MYSQL=TRUE
#            - DB_USER=vkbot
#            - DB_PASSWORD=121asdfFFFfff3dsfh23
#            - DB_HOST=mysql
##            - DB_PORT=3307
#            - DB_NAME=vkbot
#        links:
#          - rabbit
##          - redis
#        depends_on:
#          - rabbit