# Generated by Django 2.2.2 on 2019-06-21 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название типа остановки', max_length=100)),
                ('description', models.CharField(help_text='строка помощи', max_length=500)),
            ],
            options={
                'db_table': 'platform_type',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование маршрута: 10/2, 9а, 15 и т.д ', max_length=100)),
                ('description', models.CharField(help_text='строка помощи', max_length=500)),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(help_text='долгота', null=True)),
                ('latitude', models.FloatField(help_text='широта', null=True)),
                ('description', models.CharField(help_text='строка помощи', max_length=500)),
                ('next', models.ForeignKey(help_text='следующая точка маршрута', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_point', to='route.RoutePoint')),
                ('prev', models.ForeignKey(help_text='предыдущая точка маршрута', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_point', to='route.RoutePoint')),
                ('route', models.ForeignKey(help_text='ID маршрута', on_delete=django.db.models.deletion.CASCADE, to='route.Route')),
            ],
            options={
                'db_table': 'route_point',
            },
        ),
        migrations.CreateModel(
            name='RoutePlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название остановки', max_length=100)),
                ('longitude', models.FloatField(help_text='долгота', null=True)),
                ('latitude', models.FloatField(help_text='широта', null=True)),
                ('description', models.CharField(help_text='строка помощи', max_length=500)),
                ('next', models.ForeignKey(help_text='следующая точка маршрута', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_platform', to='route.RoutePlatform')),
                ('prev', models.ForeignKey(help_text='предыдущая точка маршрута', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_platform', to='route.RoutePlatform')),
                ('route', models.ForeignKey(help_text='ID маршрута остановки', on_delete=django.db.models.deletion.CASCADE, to='route.Route')),
                ('type', models.ForeignKey(help_text='ID типа остановки', on_delete=django.db.models.deletion.CASCADE, to='route.PlatformType')),
            ],
            options={
                'db_table': 'route_platform',
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['name'], name='route_name_a25645_idx'),
        ),
        migrations.AddIndex(
            model_name='platformtype',
            index=models.Index(fields=['name'], name='platform_ty_name_ec03cb_idx'),
        ),
        migrations.AddIndex(
            model_name='routepoint',
            index=models.Index(fields=['prev', 'next', 'route'], name='route_point_prev_id_53e19f_idx'),
        ),
        migrations.AddIndex(
            model_name='routeplatform',
            index=models.Index(fields=['name', 'type', 'prev', 'next', 'route'], name='route_platf_name_ccca1a_idx'),
        ),
    ]
