# Generated by Django 2.2.2 on 2019-07-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformtype',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описани типа остановки', max_length=500),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание маршрута', max_length=500),
        ),
        migrations.AlterField(
            model_name='routeplatform',
            name='description',
            field=models.TextField(blank=True, help_text='Краткон описание остановки', max_length=500),
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание точки маршрута', max_length=500),
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='longitude',
            field=models.FloatField(help_text='долгота', null=True, verbose_name='Долгота'),
        ),
    ]
