# Generated by Django 2.2.2 on 2019-07-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_auto_20190703_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(help_text='Наименование маршрута: 10/2, 9а, 15 и т.д ', max_length=100, unique=True),
        ),
    ]
