# Generated by Django 2.2.2 on 2019-07-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_auto_20190707_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformtype',
            name='name',
            field=models.CharField(help_text='Название типа остановки', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='routeplatform',
            name='name',
            field=models.CharField(help_text='Название остановки', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='routeplatform',
            name='route',
            field=models.ForeignKey(help_text='ID маршрута остановки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='route.Route'),
        ),
    ]
