# Generated by Django 2.2.2 on 2019-08-19 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_auto_20190707_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(help_text='Номер датчика системы слежения', max_length=255, unique=True, verbose_name='ID GPS/GLONASS')),
                ('name', models.CharField(help_text='Сокращенное название для внутренних целей и удобства', max_length=255, verbose_name='Название ТС')),
                ('licenseplate', models.CharField(max_length=55, verbose_name='ГОС номер ТС')),
                ('type', models.CharField(choices=[('bus', 'автобус'), ('minibus', 'маршрутное такси'), ('trolleybus', 'троллейбус'), ('tramway', 'трамвай')], default=0, help_text='Тип транспортного средства (Автобус, Троллейбус)', max_length=15, verbose_name='Тип')),
                ('model', models.CharField(blank=True, help_text='Наименование модели ТС (ПАЗ, ЛИАЗ и тд.', max_length=255, verbose_name='Модель ТС')),
                ('techquality', models.IntegerField(choices=[(1, 'не находу'), (2, 'плохое'), (3, 'удовлетворительное'), (4, 'хорошее'), (5, 'отличное')], default=4, max_length=1, verbose_name='Техническое состояние')),
            ],
        ),
        migrations.AlterField(
            model_name='platformtype',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описани типа остановки', max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='platformtype',
            name='name',
            field=models.CharField(help_text='Название типа остановки', max_length=100, unique=True, verbose_name='Тип остановки'),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание маршрута', max_length=500, verbose_name='Полное название маршрута'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(help_text='Наименование маршрута: 10/2, 9а, 15 и т.д ', max_length=100, unique=True, verbose_name='Краткое название маршрута'),
        ),
        migrations.AlterField(
            model_name='routeplatform',
            name='description',
            field=models.TextField(blank=True, help_text='Краткон описание остановки', max_length=500, verbose_name='Развернутое название остановки'),
        ),
        migrations.AlterField(
            model_name='routeplatform',
            name='name',
            field=models.CharField(help_text='Название остановки', max_length=100, unique=True, verbose_name='Краткое название остановки'),
        ),
        migrations.AlterField(
            model_name='routeplatform',
            name='type',
            field=models.ForeignKey(help_text='ID типа остановки', on_delete=django.db.models.deletion.CASCADE, to='route.PlatformType', verbose_name='Тип остановки'),
        ),
    ]
