# Generated by Django 2.2.2 on 2019-08-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_auto_20190819_1100'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='routeplatform',
            name='route_platf_name_ccca1a_idx',
        ),
        migrations.RemoveField(
            model_name='routeplatform',
            name='route',
        ),
        migrations.AddField(
            model_name='routeplatform',
            name='route',
            field=models.ManyToManyField(help_text='ID маршрута остановки', null=True, related_name='platforms', to='route.Route'),
        ),
        migrations.AddIndex(
            model_name='routeplatform',
            index=models.Index(fields=['name', 'type', 'prev', 'next'], name='route_platf_name_84d143_idx'),
        ),
    ]
