# Generated by Django 2.2.2 on 2019-08-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_auto_20190825_2227'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='routeplatform',
            name='route_platf_name_84d143_idx',
        ),
        migrations.RemoveField(
            model_name='routeplatform',
            name='next',
        ),
        migrations.RemoveField(
            model_name='routeplatform',
            name='prev',
        ),
        migrations.RemoveField(
            model_name='routeplatform',
            name='route',
        ),
        migrations.RemoveField(
            model_name='routeplatform',
            name='type',
        ),
        migrations.AddField(
            model_name='route',
            name='state',
            field=models.IntegerField(choices=[(1, 'Создан, не настроен'), (2, 'Задана последовательность остановок'), (3, 'Заданы точки на карте')], default=1, verbose_name='Статус маршрута'),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='route_platform',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='route.RoutePlatform'),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='route_platform_type',
            field=models.ForeignKey(default=None, help_text='ID типа остановки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='route.PlatformType', verbose_name='Тип остановки'),
        ),
        migrations.AddIndex(
            model_name='routeplatform',
            index=models.Index(fields=['name'], name='route_platf_name_6efc5f_idx'),
        ),
    ]
