# Generated by Django 2.2.2 on 2019-08-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0008_auto_20190825_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeplatform',
            name='latitude',
            field=models.FloatField(help_text='широта'),
        ),
        migrations.AlterField(
            model_name='routeplatform',
            name='longitude',
            field=models.FloatField(help_text='долгота'),
        ),
    ]
