# Generated by Django 2.2.2 on 2019-09-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0009_auto_20190825_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeplatform',
            name='order_number',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер остановки  маршрута'),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='order_number',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер точки маршрута'),
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='route',
            field=models.ForeignKey(help_text='ID маршрута', on_delete=django.db.models.deletion.CASCADE, related_name='points', to='route.Route'),
        ),
    ]
