# Generated by Django 2.2.2 on 2019-07-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '0002_auto_20190703_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformType',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('route.platformtype',),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('route.route',),
        ),
        migrations.CreateModel(
            name='RoutePlatform',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('route.routeplatform',),
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('route.routepoint',),
        ),
    ]
